// reactjs/src/components/Form.js
import React from 'react';

export default class Form extends React.Component {

	constructor() {
		super();
		this.state = {
			title: ''
		};
	}

	onChange = (ev) => {
		this.setState({
			[ev.target.name]: ev.target.value.trimStart()
		});
	}

	onSubmit = (ev) => {
		ev.preventDefault();
		this.props.addTodo(this.state.title.trim());
		this.setState({ title: '' });
	}

	render() {
		return (
			<form className="item-add" onSubmit={this.onSubmit}>
				<input
					type="text"
					name="title"
					placeholder="Type a new item here."
					className="input"
					autoComplete="off"
					required
					maxLength="48"
					value={this.state.title}
					onChange={this.onChange}
				/>
				<input
					type="submit"
					value="Add"
					className="submit"
				/>
		</form>
		);
	}
}

// vue/src/components/Form.vue
<template>
	<form class="item-add" @submit.prevent="formSubmit">
		<input
			v-model="title"
			type="text"
			name="title"
			placeholder="Type a new item here."
			class="input"
			autocomplete="off"
			required
			maxlength="48"
		/>
		<input
			type="submit"
			value="Add"
			class="submit"
		/>
	</form>
</template>

<script>
export default {
	data() {
		return {
			title: ''
		};
	},
	methods: {
		formSubmit() {
			this.$emit('saveNewTodo', {
				title: this.title,
				done: false
			});
			this.title = '';
		}
	}
};
</script>

<style>

</style>
