// reactjs/src/components/TodoItem.js
import React from 'react';

export default class TodoItem extends React.Component {

	render() {
		let todo = this.props.todo;

		return (
			<li>
				<span className={`item ${todo.done ? 'done' : ''}`}>
					{ todo.title }
				</span>
				<a	href="# "
					className={`del-button ${todo.done ? '' : 'hide'}`}
					onClick={this.props.delTodo.bind(this, todo.id)}
				> X </a>
				<a	href="# "
					className="done-button"
					onClick={this.props.toggleTodo.bind(this, todo.id)}
				> { todo.done ? 'Undone' : 'Done' }</a>
			</li>
		);
	}
}

// vue/src/components/TodoItem.vue
<template>
	<li>
		<span class="item" :class="isDone()">
			{{ todo.title }}
		</span>
		<a
			class="del-button"
			:class="toHide()"
			@click="deleteTodo"
		> X </a>
		<a
			class="done-button"
			@click="saveToggledTodo"
		> {{ todo.done ? 'Undone' : 'Done' }}</a>
	</li>
</template>

<script>
export default {
	props: [ 'todo' ],
	methods: {
		isDone() {
			return { done: this.todo.done };
		},

		toHide() {
			return { hide: !this.todo.done };
		},

		deleteTodo() {
			this.$emit('deleteTodo', this.todo);
		},

		saveToggledTodo() {
			this.todo.done = !this.todo.done;
			this.$emit('saveToggledTodo', this.todo);
		}
	}
};
</script>

<style>

</style>
